version: "3.4"
networks:
  happyplanter-dev:
    driver: bridge

services:
  happyplanter-api:
    image: happyplanter:latest
    depends_on:
      - postgres_image
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=happyplanterdb;username=happyplanteruser;password=happyplanterpassword"
    networks:
      - happyplanter-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgressql/data
    environment:
      POSTGRES_USER: "happyplanteruser"
      POSTGRES_PASSWORD: "happyplanterpassword"
      POSTGRES_DB: "happyplanterdb"
    networks:
      - happyplanter-dev
volumes:
  db_volume:
